// This file is auto-generated by the Flutter tool. Do not edit.
// It's used to register Web plugins.

import 'package:flutter_web_plugins/flutter_web_plugins.dart';
// Remove these imports:
// import 'package:audioplayers_web/audioplayers_web.dart';
// import 'package:record_web/record_web.dart';
// Keep other imports

void registerPlugins(Registrar registrar) {
  // Remove these lines:
  // AudioplayersPlugin.registerWith(registrar);
  // RecordPluginWeb.registerWith(registrar);
  // Keep other plugin registrations
}